common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:dBTtz1XZJ40+pAyptl7hRqY6ivFE,iv:kJ3FxyGeYKM5cI6itPjrMhUPJNBn0uudX9tEXg/8O/s=,tag:fxOdZQB+c2GYA7Sh5K76tg==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:f7xcEBMyXMNmU0CXSaJWofqXjtB0S7+mPw6n+BcCkU5qSEnZ4FDh27I9JhyZNA7wink8rmdM/N8Y/eV2Qe9LJtidskEEolw23jz/VpjS9O8by2EZZK5LNQ==,iv:o88k4zfO0J+smZYqIW1Lj42Y4dOVeL+iAqYiIcqS9KU=,tag:Owd45Hh2196g9DAuGLdRmg==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:06JjhT3aotw9m66HHLTmfFp9b/uAfv8zofg9M8NA2LQ=,iv:KXNPq1XxPjA9xNNBjHP7HOAfa8aLeYuFE0sPk+KUwOA=,tag:wOdfFNjYxOFvQpg3jgBzxQ==,type:str]
            PRESSBOOKS_ALGOLIA_API_KEY: ENC[AES256_GCM,data:xs6Om8/SISeW1D4Ci7QNv6VU9zvB0whkB0oM25z8bMg=,iv:ZqfSebpfvs4LM2T8POdIpgg0wZc/qLBabv0xHRU3hl8=,tag:Fd/Jt4WAGR6qJPpDhjwLbQ==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SnVZeVlkdWU3SXoya3p5
            Mm92K2UxcVF2bU9WRXF4S0xxRXkxMHJYM0hzCnlyaEhTTXppMGlIM1ZTdk1EaXFE
            Wk9QSFJjMElXTi8rdWVBZktWVjZwSjQKLS0tIEJ0cGhoM0IzbU9lMU1SVCt0WGRH
            UWlxWmV2UnNsM2tBcE1mdVV0ZWc3a2sKtd7IO0flwhWyYsbRqnKyuDP+b+K/ICjw
            mhaEwANBrPTLnp56lIJlfxi3ERz/CqD5eA+HhErxrWzdEydmIX3Amw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTXJyeEx0UzBrY09uWjQx
            QmpveDNySndPNWt1NGNIbHJjS2ZrZUdzU1ZNCjlIeEMvd3FxNGF5RnZWVk9kZ1RG
            OWtHK0ViQVk3ZHN5VWFjU1ZMNDg3QUkKLS0tIDJMNWMwY25nRWVoUnBRUTBTak9o
            dlhaVjVBaDJRRVp2bUt2bXVEWlVFOGsKE0toC+RdU+dCwJXt4jtQ28sOtm69Q6gs
            Msl6B/lZmQMh6msM9cNpl/gAbO4Nm6EBpyN2p6aHnBBFXzsn3Uup7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWVJ1dXh6TCtoUTJ1VEZ0
            bHc2ODk0K0t4QjREd04yb0Z0L3VwTEdKT24wCmdVNUZNSTUwdW42RHR0RUp2N1hV
            bEZpNjU3Uk1JbmFhU3lubW9sZDBZQmcKLS0tIEVhVXZHcXhYVWUrelJ2U3VZTXlI
            U1NicmQ3bmZPSlpzUEhTOVFxYStMVUUKTeW6qCUpU8T7VCRxvGNPv2tL/F9PJAYP
            aPwgso7Hw/CPh9vOnvlVTRmSM4Njc3eYxEmdy7Lovhc6bSt8uUNcDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc2NXb211Y3NIZE04d2xp
            bUNkUGxEaTB3V0xTV2xXOW4vWVdFa1NhOTFzCmhrV0V0bG9STHF4YThnZld6dldh
            Q29XQzJheko4N0djNEdYb05LRWYzbmcKLS0tIFJPbUhZRHlCNmdOcmw2NFBNc2lP
            RlRXbEphRjcwbFJiZlQyb09SNlBGcGsKpwuA0ze/wIv0nj19N+hCf3DvBqd8ljRG
            0jDV6pZyqDkcF3mEcT+Wc9xUG318CMqeYu47gtTH/LO9K/NOEOfPNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS054YWhDa3lNMDFjS1I1
            bGJUMWZnT0MxWG45TWwyaVNUUW00a0ZyYVdFCjVVRzkvcEoyZVJhWjBSQ05FdXYr
            bkdFR2l5VTRWNE1DendVY3IxMHEyTm8KLS0tIHpTdXY3WWFFUTJjb3pFMHAzaVhY
            czhhNDJMMzZMN1p1b3llZGVuMWxhWk0Kda7UcxmS1bwZoJ1cqBT5o7iKIDObfpqA
            TrkYmOkIkBD/rq/8KH7USbaGjgW1+Wh5rJFgg6aWbaZJ3C3vKXjCKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M3lwWFhRTjhHdFQwM2xw
            aHFDQXdjbTdNRFpoMVJrZE5hNEpUTkdXeG4wCnFuTUVYckZ4RmtyVEtGWmdNaVl6
            cmo4Vzc3UFNMU0szU2h3dmJtZlNTRVUKLS0tIHpjd1Y3b3B6OEg4eENkOFg1WDJz
            MXF1OWI0dTdEN1FwYXB3em9zZzJpUVEKgtLYY26QFERoVr4JRP1xqkeNJXA8rwaD
            hJ10uNd1FIp/5DgzIvZa4Q5RgVygUAyAwLxHNhIrKrXB+LDujDmyLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T09:02:18Z"
    mac: ENC[AES256_GCM,data:6qi4mbnIC2iucESWWJU6Yan3xKsj255L6s98VOVNrb7PL9Qqllxpb1999geEJg6qUCtv/3Omp73GUzlt57Fxo5TEZ5l0PtBArasnpB/gswmBPAyvCDDYOhVA/UQMt0aCnJOxSW4ArZzHEhsu6RsLFPpxBFuTFF/S0iOpJaoQAR4=,iv:zj1OJRiljv1bXFAm089gIjzPEgheBRzN5SOLr7flbZo=,tag:4Z0hQMTxgmtvy7zayiBlaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
