common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:LoXu/qiL6ggYBs9rnxA8Ox6gBox+,iv:KmybIangYaxzo802Vt93DsA0cE/mrFhuS+GQrkCE32s=,tag:sBhgR7jFuaqRRJd9MBMQag==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:Uw3oU4eekvtn6HNGWSBMSikvMkAp+pNAMZ8Ccm+DX2mGIaK0v4+nPX7U+KzjFNnw994fGdThPKJK+8fM/yPLaIhV29Lww0b65yO+qtgVfIQLpe3TSnlyNQ==,iv:YnjbCUXmf6055PH1Yw6PoY9GpG8HCZGyWKX0l+XL7O4=,tag:/PH3A94j4nDQ43Y0RjWu5Q==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:vA2GWWIxov/tlWTjGbkQCo+5ZiyW6ADdQ1x+UG/Lprs=,iv:mSNX11/CKeucWGQ86oSCXJqWTMFsOj0E2axcPOnj8As=,tag:vAArGAhDkBMUdOOlXX+suQ==,type:str]
            PRESSBOOKS_ALGOLIA_API_KEY: ENC[AES256_GCM,data:KsjbffZzReG3nn5EYDDD+b1BkTjUFQbQEqlDBKmn8xo=,iv:xj8x2zegBuNkrG8fDOMb6zYOwZsW7A111W81Oz8pz2E=,tag:JHAIt/rtl5KrV1lYAsPZ+w==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleXA4NHp0cDJTdk1YRjNW
            U3M4VDJIcVcwZCtQQTlXdSttSzlMeWs0d3pzCjhtVWRWZEIrMUNxaklJeFc0ZE9i
            YisrVk9uOWV2UE1ZT2ZIb2l1U1RRV3cKLS0tIG9Mb3Z4T05CdFFaVnQ2RlUremEz
            YVh3SWpySWlHNUQ2UTBvVXljR0l5b00KARVakXQH0ClbcHiWq5UCy9khPkSrmN3s
            sI84cD3qHbLv3DhCL+vzTzT/pV9DZ4Xj/U6KH7n5QfpucX4RFg086A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RDBHRjVVMUYrV3E5cFQr
            VXNDZWpyKzM4aGhRcmJ3b1NWdVdKM0F4WkhVCmp5L2s0ZittL0Z2RzIyZWhENFZI
            KzNkVER4TVllM2kzQk1UYTFLbUpwc0EKLS0tIEZURnlMblZHcWpiR0pqcVJFSDRk
            SGVSYzQ0VjBwNVVUUjBQN3J4UzF4MTAKT3tBmdONVdaJ9jp3cUT69ZSG0fjEbRr1
            oI/IGkxoEzQoVXeqovRveOMjy0FMHXhzdHggt9llKUslu/f04tHywA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZjgzcmVZUUJvLzNFOU9s
            MzdwM085eEN2L0k3dUtqeExrUG1HSzU0OUVNCkM4VDFucENHaFB6cGJIOEs0Rm0z
            c3ZEWDRlbjNwbzQ3N2V6RXJwMitqVUkKLS0tIGd1Q3VLeEFlRTVBTTJTQlEwbDB5
            ZFlVV3U4WERlcGxrYmExS0dncDA5UXMKKS3IjjchkNkBhDZtWFEyL1qF8Ema8qDv
            oBTurRYrjUgoiphSjbhoTVyKJ3DIWK6XB/DmMyuKCxfuTGIyODIVPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ1l5cWFVWDhoTzExeTk3
            RFgwN3NqTHY1MCtRZlFKMkE5NUFEY1lDVzBBCjJkclVMT2xLWUpjOW5tMWs3d20v
            N2N3UUp0alNYM3hYZ0hNNXc3YlNVbVEKLS0tIHptRjNnRDR6RXQvbFlHcmJqMHp6
            YWFYLzc3a0Uza0xyajhtOWpnZ2NsRU0KVBhJzAr3Hu93F0S4vMbc26vt8dhh7YyY
            Yc5sJC/S6hAY2zGYswrdVao20mJ7QGZdUxW7reR9R9To1G9WyemMpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VW0yUitUNU5qZ1JQSk5G
            OGhMcEIyWU9GaGVSUVhvdURPb3dvcU5SM1FJCk00THRWMTVaY3hsYjUrdUw4SUtO
            ekJLVVpLWGNVVU05MmpxUU9hSlJSWHMKLS0tIGdsd3RDa0ZLNXdvQ00rQzR1TWl6
            WUwvOVhPd2ZobW03L2JUOUEvS2lXMjgKnpYrj48KnNrqKdo3a/iPaCKTapbVRUfi
            OjBhHUjrUKqi9Y80k3HHtOkQ1C3hcrZragQQZe52leQi4XSjwt/5qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS1Y4dWtnL0s0ZUs0YnVR
            dmd3UTZwK0Q0ejNIY0JVb2F4QS82SlVtUWlFCjdYSUliazB5UlEvY1Q5YkFTQ1dN
            Yi9wbU9oa0lvNnljbkhUbVN1ekRmLzgKLS0tIGJDcTVkckMzU3NzYjJZZEhoUWFv
            bDY3YlFGdGN1MnlTY0EzNTNhcFV3cUEKNyNfoQHRMZEX9HubVa/CE06RKBbea4Xr
            pKGElwiAqQo//f415Z4/TnX0BMp9rrhQckZmpG3ij9TTgG7corVxpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T15:01:26Z"
    mac: ENC[AES256_GCM,data:T1Hl6EDIEFpTRb6MCvoqrnyDBdpj8pDgpkOFSo+ezEEtpjjoh7oJ1wBcK4SiJja9NdaaDGoWDyLpKgUCkIMpnBT+GNQ1DMZrvADS0dl/Mw97UxOlG3DVTmz4FfR7D4LuzmUuEImnrf1JtIv9GK6I9BNm+G2GR8UrA2jXxH/Eaqo=,iv:HiuB40zREw92h1fO2EuHjNMUV3F4aY3CCpocTRSo95o=,tag:upFDaXGKpKAbjOwtUFhbIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
