common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:TTnmaNMvpMBdYCFqZzsdpvf4cop7,iv:5WlCqEsHjuKK3TVo2gI+wAHYYr4gSb6sz1JapF3tBaM=,tag:AaLJK2amiHQWY+/5skAwHg==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:oeZWh5vRLBfsFx5OYNeiEdUAFIpOttycnZ7uKokGjOVQpEn48GOzXr5OQHGBrChVwDKiM64boQ4wJZV0je9LhWOMMCg8Rq5412MHmx15k0OBlLE242Kt/A==,iv:1ZukxZcsm1OgZR1hzq2WBxwAhY/BMWJsyY9/fv4tPkc=,tag:/X6DU1TShnh3V2PSE53skQ==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:DtgNhG2Jg3mpdPn389MUfnkzpZ6oo02a97W37+HqpyE=,iv:iNuxmMDgQryy1gMMVZjlL8Yx50EHeU1GKKugfyQ7vDM=,tag:kGNKHf2aexfKYyUyfiCypA==,type:str]
            PRESSBOOKS_ALGOLIA_API_KEY: ENC[AES256_GCM,data:XAT83ftHHz4SIaWmmjFaoWpr2bVNeW1CJhllRJ9afwc=,iv:Odlsb9gMmX096S+ZDUhZEjU/T6Sm9c1GkqeCuqtqyVc=,tag:nrxvbU91DtfU88xLGke9bw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNjlNWG5vT2xyNDBxSzc0
            dmRVcDA5SHVxMnJuUTRvcVZOc2lEMENKbEdZCkRhMFZBWVZFb3JkZjZGMWpIcTlw
            R3lRL3Y2ajAyRHZSRTFGYUpCTTVrdVUKLS0tIEpiSjF2MnVQSXhheS9BcU1Cc044
            cjVkOE5PYlAyVHNwcWljOG5CTUNzQlUK+vS59JRx/vS+zvAorW/UhAYrQWKZjGjm
            NuNU30JfwurytkxaBwduAwpSFJRbLwIz6oBWaw16T6EyH+9sCYsFHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMXNRZFhQejEwTW5vS1Jl
            TjdsQ0liL3M4STRZanlyd0V5akJaeTdycGwwCm9pRlpvSDczTDRGSVpSTm5scUs2
            SEduaG02NTBsazNvT0ZjeXdoQm9VT1EKLS0tIEhCa1VQaWc3eFdDeGdXNHdRTzZq
            czlUbldySGZQUVIxYU5XYnFQMTMxMDgKCBYzXhEGN34H9qB4AJtb/tQlAVbZv4rj
            um/z65FgdQiFpYj8PTFk9L/ba/X7BUxeHI/goKVw7cX0Zo65LgA4EA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVXBaaUUyQjBNUmVQMnlG
            MkxubFBPS0ZvQitkTUFKTjVyM2FMQlVWNWhrClJKMjdJZlUxL0gxU0gyeDZva0xH
            N2FHdnBuWG9wczFZMmxicWc2aTIwYmsKLS0tICtPMlcyMEpiK2VkWGFoNG1tWVh0
            SkFKbDI4MnV0RGtDczBoMks2RVBDbEUKMosZuFOKsQH9YeVYDWG7k571NJPaxZtz
            VW05RRTkdsLmEW3gpSEcLBNGS2qt0i5FtOlMdn/detErCYCzswOJ/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U3pENjlNY0dyVXdvQTBr
            R1F1SUNXdGpKQlpUQVRXb0oyZU92WVJFUGxrCkNnOVg1TXU4bXVMYThJQ3VvczEx
            SWZmSEhXYlQ2TTkrcFdvYnhxNHpibzAKLS0tIFZPc3ZaOWdMTGR3MitXb3dTU3lR
            M2w2U1lJQXpNTUNMLzY2SFYzT0lsVHMK7eLX65AhrRmRH7ZjOOxdnuOtYaVT7Tgb
            Wd3I/udGv1vunIvbUijgYulCTUoEOfL86i2vEie3/JlyCCkYyZyQsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL2lsT2ZocEZTTjBMOFls
            Rno0dERXN0gwY1A2N3ZFVkkzTThBUXlwblRBCml1NlRLZ1U3TW50Y2lSUXYvamdM
            T1F1eGRycEpzdXVZZG5FTEY5S2tDQUEKLS0tIHAwTTgzNVJQZ0pkWUpwR2VjMDBy
            U2dKMDJ5bGI4L0J2bmFyYkt6d1dxQXcK13ZcMPCd1mv+2nqRFmajh5ya9LB3oggA
            YYiMjIRpAZ53cbRwdeptj3Glt1jB4t/BDN4n6gJSGkbk+2Da8nOsXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySUd2UitPOU9HdHMzeDdh
            ck12ZTVjY3F2QlBhczJ6S0lHbVBaQXdPVG40CmdLZmMxZDg1ZnpEdU5EV0Qva2Jl
            ZDFWUEcvR1N2UHFiUkFFWkpkUHF0K3MKLS0tIFNheGlpNzVaeEdjUmFIZDBWei9i
            OXFwZXBvNmVDYTN5aGppUVFTSjFzZncKfxmqacUElfyxszKeUa/SZTcEiptNAOhQ
            DI1xfBHHq5pwh0xijdx2zIhKK1zf/gqlozvPFCsSDFLBiHdRmHSzAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T16:51:59Z"
    mac: ENC[AES256_GCM,data:t21RBK0vsqnIk4doDWrkQAYWANthF93+wGuYzgYp7htgMT2s1iWxhsLMGx0ZFofF6lOBVmLwf/aJHoAl30SzxzI5ZBScx3eB5cC90OrCjMfKE+2FPHXU/I4Nn+kogv9/8ocAROif6EmuuZt0tmycIVVdyvgKbGstbchAEKSFh0M=,iv:OHw9kPfW5Tz5ULayDclTzIoiSnm4KV0qB46N+d7WP1o=,tag:dFVBdKnsQRQ0imNNNf9CsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
