common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:Vxl99vx5SiPNSufyi6bNnYEZxvsMtgc=,iv:1I/7DAWi4s2TWlZeqIz2fQQ1mWduv4Tf8z5Aq0Eb+0Y=,tag:QEoG7/AeuoMd1V5Gfzl2Mw==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:JCzbKlbWrm7jzCa8Xy1vK3rGfso34HCw/v25hZrjHDKj6Kvk3PHp4kqgBm4rMKOzBYL/fy7P4IKA7JheEbd5v6GV1PPtcocqAOJP6CkqvwhsL57skd5U9g==,iv:QqkAMUnlyDMenEoVC0AyuzH6Vd7Q47R4sYJrp0aKK6g=,tag:+qQatidt/4wdvHnSoAXPvw==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:g22lNdn9RI6/zYT2g4C9XiPB,iv:PpKdfwAWeD4/eTndmlGVsiNV+UIdi44JSOFLrc/y7/A=,tag:Jo2AC/QAE2eiRhRANg5VZw==,type:str]
            PRESSBOOKS_ALGOLIA_API_KEY: ENC[AES256_GCM,data:Kmiy3S7UG3BJa2NvwnHVcKXvvmcbc8/WMK0rGEgUk/0=,iv:ZEC71XA7wHd5j5zxWxnM8fPdC7RoeHUMBUyYXlS4ASc=,tag:H/MF80gr8GCjKnrKJBkz1w==,type:str]
restore:
    config:
        sensitive:
            ADMIN_POSTGRES_PASSWORD: ENC[AES256_GCM,data:wGvnoSm6IB+HMAEg5kuhxySY,iv:ZOOZ/mRuJvw1WaqI0Ea5ksWiCG/UwgUACh2bT5DmG5c=,tag:HG1aKrCbOYu4jrZrlmmbmQ==,type:str]
            ADMIN_POSTGRES_USER: ENC[AES256_GCM,data:oLJvogy/ZSPsufc6DqjOEfs=,iv:I7E7ki/NW7sLMDxu0+8xWwq7dT1pJ9HNsVde66W67xM=,tag:jllVauKo0mNu8eUXKbiERg==,type:str]
            AZURE_TENANT_ID: ENC[AES256_GCM,data:vTKX9g5GCLSAJPuhZopguSrXM+t07TOB5vxTEqE3qkC1IX/q,iv:Kt3PCQwm8oIvTlw3f7KzHARH3Y+i/Mn4wVgOrdvt7fc=,tag:vMoPObALJPQJr5gHqf7dBA==,type:str]
            AZURE_CLIENT_ID: ENC[AES256_GCM,data:YIdWkZvZTz1teytYIXTuGTvyIpnAwOPZRr0r9VXPbz6EHHy6,iv:PB+VWJFKb0EoexO+XH0XYZh1LJKuYPbmKNCLCi2wOM4=,tag:xpCYWZIQ+OeFMUm0dbLQpQ==,type:str]
            AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:H7/ZwL72b7bkXl2Kq75vyB0u02h+j4NrzM3p3dpdm6NLGZzWbSyg2A==,iv:3kYVJ0m+qAACyPEPi0xzX+aoJV8DLgSkjEaaqtMCkf0=,tag:/4ElTQdeBtG4PUEwdhA0yQ==,type:str]
sops:
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRlgyM0czeUVMMituL01K
            cEJyZGdJQlFGa1hUblRPT1dyaU1abm9KWEVBCmVIWlNPamJmMVpGbTVxMTFpYVRB
            UmJvQnJiS0VxSmdId05lRXFlKzdDZnMKLS0tIG5VWlpmejlUQmVKd3FOZGhsZC9T
            S3pQdzlYRU5XM2ptUXNscGpRYS9KWGMK92hCUXV6MM3dSD0erd/mcfTxKPc+hu0K
            IHG/DMTUtx9owids8o9eUy71KZeyVA8Z7Hxnse3NZKerlOuAiql0+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenRZUmw1UzZRLytLV0d0
            OHRuTjBlQmozU2w0ekNEODFuQW05VUJjQUcwCnNxWkpOU2FNak1hNWxmbkcwUjhr
            amIrdTRDaHZZazJxa1MrYUVjZ0g0bmcKLS0tIDU1azR1MmZsRjlaZUVOdlBLcmQw
            ZmNGc2g0NlRIZTljaExOSHMzU09hSncKg7t97iLHXB1deOHGNCYVUBT4Qr89BtzH
            zhCoIDJ+QCokzdhTo/gSA4pADE5AIP5aYeydR+YBECOqze1H/Lmc9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1lMclJlVzIzb0toMFRH
            MmdCK3p3ZmpPZklZUjlNRGNHQnhmZDlZY1FZCktlTjVycG1iSHhxRm9ibWpMQmk1
            MGd4dmlyK0QxMy9aRWtMR1VlVFA2WncKLS0tIDRaZXo2VjhCcDVnaW5XRENFenpR
            Q3l1WWppQUFyMzlPOVBEb2lpd1daODAKvrSvljXoV1va6dfxGYpOYwVFyuEBlAGN
            arpP/6FqT9KTVTVkxXhHQ0fjfMUEQglwsHmSW7FjeioDZHGgm013bA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYUt4MVhGbFRORzVKQkFy
            cGpiL2kzUDJ6V2lWN2tYK3hqNzVQemtmNURZCjNBaW1jZlQ4ZnRCdWtDYmwySzY2
            WkRjSDRVcUptMTNhQXJmZzQ4NmhyRjgKLS0tIGh6TFdFUDFvaXpxTS9WS2Z4L0Zj
            YktWYlVrYkd6L0YyQnNSazZWVXJNQkUK57GKjBI3jVjg/ek+Q1JKMP2qqojZaOsX
            WzFHA+CbsS0vlP0xU736rjECLMoK1zX0vNUW3+CoWjPXWUSc4mMfkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidmNGRFFTeVg4dXlpUUJX
            RCtXUEFCdTI5emM4MFUxM3V4SGkzOXNHQmpZCnBjbWIzTDM5ZUNFYytic3RJenlT
            VW9OTDNKOUdrRjJFUnNyU2VTcWVqazQKLS0tIHAyQmJiQlV1QVhLR3c4S0ZMSU53
            dXBqZ2h3YUlhTVFDeHc3YmhCZGdVOEUKrOY+uv4q36ZSPLod4GSjirG07u7mu0lb
            EC3UEfvEQ/UPKX5n4Qtq7yKufYqKtbNGW3gneZdIiBXvqtTBIoGDrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYjVOZGY3S3JJVTF4UmI4
            M0dBblZnREkxOUZuK2pybEJGV2FKRTZwVlVvCkdHSXFmT2grOXZOdDc5ejhGcEN1
            REJzeDBQTzF2dkxwbXdRckF2YVYrdWMKLS0tIFYyVHRnOU9HYWZGTS81N2R5dEFM
            b1lBNitwR0NnbThuZnRNdEYrbngrQVkK0TkIJ5koxNCG+VpO5zUoFS6WMZhRNGFM
            xWAkEiKlqTac0cWeHhgoclzXF2SwyPecRB1SRbpc+vOm3CVhwW/nwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T09:02:26Z"
    mac: ENC[AES256_GCM,data:/j5z5MKxpQsQQPDjWrR/ta5RTmnrUsxOiFB4APKWQ+82ZaozaWNlrnlQuCF2TEG/wFETlk8FTuVte2ASWujDzSu0ZD95nxqJ1sB4GKiPHNgkCLHxpCBYBxtdM22eU0VKKVGNWamVzvIJjTSNzBcsDH29Lzfo4W51l9qpFAc0p3g=,iv:fAtHx7GIpC8gattl8lagS/oKmButa3CqyHIWXOQWpmY=,tag:f742hFBxxt0lCDgN0zzjCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
